### ISSUE TITLE
error paper_vs.py

### ISSUE THREAD

**Issue by yani-rl-ai** [griffbr/VOSVS#1]
hi @griffbr, i am HSR user. i have followed your instruction in this github. 
when i run the paper_vs.py,, it has an error but i can not figure out the reason. previously i installed matplotlib2tikz but it does not work.

this is the error : 
<hsrb>~/VOSVS/robot_exp$ python paper_vs.py 
Traceback (most recent call last):
  File "paper_vs.py", line 20, in <module>
    from data_log_utils import *
  File "./misc_fun/data_log_utils.py", line 10, in <module>
    from matplotlib2tikz import save as tikz_save
  File "/home/kubotalab/.local/lib/python2.7/site-packages/matplotlib2tikz/__init__.py", line 16, in <module>
    from matplotlib2tikz.save import get_tikz_code, save
  File "/home/kubotalab/.local/lib/python2.7/site-packages/matplotlib2tikz/save.py", line 237
    def save(filepath, *args, encoding=None, **kwargs):
                                     ^
SyntaxError: invalid syntax

**Comment by yani-rl-ai** [comment]
i hope you can help me for this problem. and thank you for sharing the code

**Comment by griffbr** [comment]
Hello @ROSNovice ,

The matplotlib2tikz library is only useful if you want to automatically make tikz figures from experiments, but it is not needed. I would suggest commenting out lines 10, 65-66, and 79-80 in 'VOSVS/robot_exp/misc_fun/data_log_utils.py'. Let me know if this doesn't work.

Best,
Brent

**Comment by yani-rl-ai** [comment]
Hi @griffbr thank you for your rapid answer

i did as your instruction. however, the robot is not executed directly and this is the result 

~/VOSVS/robot_exp$ ./paper_vs.py
2020-02-12 16:48:15.026924: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2020-02-12 16:48:15.026946: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2020-02-12 16:48:15.026953: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2020-02-12 16:48:15.026958: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2020-02-12 16:48:15.026963: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Restoring parameters from ./data/models/bn/bn.ckpt-1000


Robot moves next, make sure that you are ready!


INFO:tensorflow:Restoring parameters from ./data/models//bn/bn.ckpt-1000
Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:

**Comment by griffbr** [comment]
Hi @ROSNovice ,

This is normal. IPython.embed() (i.e., 'In [1]:') is just pausing the program right before the robot starts to move. Type ctrl + D and then enter to continue. Just be aware that the physical robot will start receiving movement commands after this point.

**Comment by yani-rl-ai** [comment]
Hi @griffbr thank you for your guidance
